# Generated by Django 6.0.3 on 2026-04-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_mgt_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("director", "Director"),
                ],
                default="student",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
