# Generated by Django 5.0.7 on 2026-05-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_mgt_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_name",
        ),
        migrations.AddField(
            model_name="form",
            name="attendance_percentage",
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name="form",
            name="capacity",
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name="form",
            name="class_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_class",
                to="school_mgt_app.teacher",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="school_mgt_app.form",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="assigned_forms",
            field=models.ManyToManyField(
                blank=True, related_name="teachers_assigned", to="school_mgt_app.form"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Class",
        ),
    ]
